/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd.Fornecedores;

import Class.Fornecedor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import projetobd.Main;

/**
 *
 * @author aliso
 */
public class TelaFornecedor extends javax.swing.JInternalFrame {

    private boolean atualizar = false, excluir = false;

    /**
     * Creates new form TelaPedido
     */
    public TelaFornecedor() {
        initComponents();
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
  
        jPanelConfirma.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCadastroPedido = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldTELEFONE = new javax.swing.JFormattedTextField();
        jButtonCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelERROCPF = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldContato = new javax.swing.JTextField();
        jFormattedTextFieldCodigo = new javax.swing.JFormattedTextField();
        jPanelConfirma = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonConfirmaSim = new javax.swing.JButton();
        jButtonConfirmaNao = new javax.swing.JButton();

        setBorder(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText("Forncedores");

        jTextFieldNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jFormattedTextFieldTELEFONE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldTELEFONE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonCadastro.setText("Cadastrar Fornecedor");
        jButtonCadastro.setBorder(null);
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Telefone");

        jButtonBuscar.setText("Buscar Fornecedor");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar Fornecedor");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir Fornecedor");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Endereço");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Codigo");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Contato");

        jTextFieldContato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jFormattedTextFieldCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelCadastroPedidoLayout = new javax.swing.GroupLayout(jPanelCadastroPedido);
        jPanelCadastroPedido.setLayout(jPanelCadastroPedidoLayout);
        jPanelCadastroPedidoLayout.setHorizontalGroup(
            jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldContato)
                    .addComponent(jTextFieldEndereco)
                    .addComponent(jButtonCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldTELEFONE)
                    .addComponent(jTextFieldNome)
                    .addComponent(jFormattedTextFieldCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelERROCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jPanelCadastroPedidoLayout.setVerticalGroup(
            jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelERROCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("Confirma?");

        jButtonConfirmaSim.setText("Sim");
        jButtonConfirmaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaSimActionPerformed(evt);
            }
        });

        jButtonConfirmaNao.setText("Não");
        jButtonConfirmaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfirmaLayout = new javax.swing.GroupLayout(jPanelConfirma);
        jPanelConfirma.setLayout(jPanelConfirmaLayout);
        jPanelConfirmaLayout.setHorizontalGroup(
            jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                        .addComponent(jButtonConfirmaSim)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonConfirmaNao)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelConfirmaLayout.setVerticalGroup(
            jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaSim)
                    .addComponent(jButtonConfirmaNao))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(jPanelConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelCadastroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(jPanelConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jPanelCadastroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        
                jPanelConfirma.setVisible(true);   
                jLabelERROCPF.setText("");
                atualizar = true; 
        

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
                jPanelConfirma.setVisible(true);   
                jLabelERROCPF.setText("");
                excluir = true; 
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConfirmaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaSimActionPerformed
        // TODO add your handling code here:
        if(atualizar){
            try { 
                this.atualizarFornecedor();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                jPanelConfirma.setVisible(false);
            }
        }if(excluir){
            try { 
                this.excluirFornecedor();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                jPanelConfirma.setVisible(false);
            }
        }
        
         
    }//GEN-LAST:event_jButtonConfirmaSimActionPerformed

    private void jButtonConfirmaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaNaoActionPerformed
        // TODO add your handling code here:
        atualizar = false;
        excluir = false;
        
        jPanelConfirma.setVisible(false);
    }//GEN-LAST:event_jButtonConfirmaNaoActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        try {
            // TODO add your handling code here:
            this.inserirFornecedor();
            jPanelConfirma.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            this.Fornecedor(jFormattedTextFieldCodigo.getText());
            jPanelConfirma.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    public synchronized void atualizarFornecedor() throws ClassNotFoundException{
        int id;
        if((jTextFieldNome.getText().equals("") == false)
            && (jTextFieldEndereco.getText().equals("") == false)    
            && (jFormattedTextFieldTELEFONE.getText().equals("(  )    -    ") == false)
            && (jFormattedTextFieldCodigo.getText().equals("") == false)
            && (jTextFieldContato.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                
                    dados = new Fornecedor(dados.getIdFornc(),jFormattedTextFieldCodigo.getText(),jTextFieldNome.getText(),
                            jTextFieldEndereco.getText(),jFormattedTextFieldTELEFONE.getText(),jTextFieldContato.getText());
                    Main.atualizaMysqlFornecedor(dados, 2);
                    jTextFieldNome.setText(dados.getNome());
                    jFormattedTextFieldTELEFONE.setText(dados.getTelefone());
                    jTextFieldEndereco.setText(dados.getEndereco());
                    jFormattedTextFieldCodigo.setText(dados.getCGC()); 
                    jTextFieldContato.setText(dados.getContato()); 
                    jLabelID.setText("ID do Fornecedor: "+dados.getIdFornc());
                    jLabelERROCPF.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                 
            } catch (SQLException ex) {
                Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                 excluir = false; 
            }
        }
    }
    
    public synchronized void excluirFornecedor() throws ClassNotFoundException{
        int id;
        if((jFormattedTextFieldCodigo.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new Fornecedor(0,jFormattedTextFieldCodigo.getText(),"","","","");
                dados = Main.atualizaMysqlFornecedor(dados, 3);
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCGC())){
                    dados = new Fornecedor(dados.getIdFornc(),"","","","","");
                    Main.atualizaMysqlFornecedor(dados, 4);
                    jTextFieldNome.setText(""); jTextFieldEndereco.setText(""); jFormattedTextFieldTELEFONE.setText("");
                    jFormattedTextFieldCodigo.setText(""); jTextFieldContato.setText(""); 
                    jLabelERROCPF.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                   
                } else {

                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                 atualizar = false;
            }
        }
    }
    
    public synchronized void inserirFornecedor() throws ClassNotFoundException{
        int id; 
        if((jTextFieldNome.getText().equals("") == false)
            && (jTextFieldEndereco.getText().equals("") == false)    
            && (jFormattedTextFieldTELEFONE.getText().equals("(  )    -    ") == false)
            && (jFormattedTextFieldCodigo.getText().equals("") == false)
            && (jTextFieldContato.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new Fornecedor(0,jFormattedTextFieldCodigo.getText(),"","","","");
                dados = Main.atualizaMysqlFornecedor(dados, 3);
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCGC())){
                    jLabelERROCPF.setText("Existe um Fornecedor com esse Código");
                    jLabelID.setText("ID do Fornecedor: "+dados.getIdFornc());
                    jFormattedTextFieldCodigo.setEditable(true);
                } else {
                    dados = new Fornecedor(dados.getIdFornc(),jFormattedTextFieldCodigo.getText(),jTextFieldNome.getText(),
                            jTextFieldEndereco.getText(),jFormattedTextFieldTELEFONE.getText(),jTextFieldContato.getText());
                    Main.atualizaMysqlFornecedor(dados, 1);
                    jTextFieldNome.setText(""); jTextFieldEndereco.setText(""); jFormattedTextFieldTELEFONE.setText("");
                    jFormattedTextFieldCodigo.setText(""); jTextFieldContato.setText(""); 
                    jLabelERROCPF.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    public  synchronized Fornecedor Fornecedor(String codigo) throws ClassNotFoundException{
        try {
            dados = new Fornecedor(0,jFormattedTextFieldCodigo.getText(),"","","","");
            dados = Main.atualizaMysqlFornecedor(dados, 3);
            jFormattedTextFieldCodigo.setEditable(false);
            if(jFormattedTextFieldCodigo.getText().equals(dados.getCGC())){
                jTextFieldNome.setText(dados.getNome());
                jFormattedTextFieldTELEFONE.setText(dados.getTelefone());
                jTextFieldEndereco.setText(dados.getEndereco());
                jFormattedTextFieldCodigo.setText(dados.getCGC()); jTextFieldContato.setText(dados.getContato());
                
                jLabelID.setText("ID do Fornecedor: "+dados.getIdFornc());
                jLabelERROCPF.setText("");
                jFormattedTextFieldCodigo.setEditable(true);
                
            } else {
                jLabelERROCPF.setText("Não Existe Fornecedor com esse Código");
                jLabelID.setText("");
                jTextFieldNome.setText("");
                jFormattedTextFieldTELEFONE.setText("");
                jTextFieldEndereco.setText("");
                jTextFieldContato.setText(""); 
                jFormattedTextFieldCodigo.setEditable(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return dados;
    }
    
    

    private Fornecedor dados;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonConfirmaNao;
    private javax.swing.JButton jButtonConfirmaSim;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigo;
    private javax.swing.JFormattedTextField jFormattedTextFieldTELEFONE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelERROCPF;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadastroPedido;
    private javax.swing.JPanel jPanelConfirma;
    private javax.swing.JTextField jTextFieldContato;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
