/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd.Produtos;


import Class.MateriaPrima;
import Class.Pao;
import java.sql.SQLException;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import projetobd.Main;

/**
 *
 * @author aliso
 */
public class TelaProdutos extends javax.swing.JInternalFrame {

    private boolean atualizar = false, excluir = false, buscar = false;
    DefaultListModel modelo = new DefaultListModel();
    /**
     * Creates new form TelaPedido
     */
    public TelaProdutos() {
        initComponents();
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
  
        jPanelConfirma.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCadastroPedido = new javax.swing.JPanel();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jButtonCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelERROCPF = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldCodigo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMedida = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMateria = new javax.swing.JFormattedTextField();
        jToggleButtonBuscar = new javax.swing.JToggleButton();
        jLabelNomeForn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMateria = new javax.swing.JList<>();
        jFormattedTextFieldValidade = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldPeso = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelConfirma = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonConfirmaSim = new javax.swing.JButton();
        jButtonConfirmaNao = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();

        setBorder(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText("Produto Pão");

        jFormattedTextFieldValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jButtonCadastro.setText("Cadastrar Produto");
        jButtonCadastro.setBorder(null);
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo do pão");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor");

        jButtonBuscar.setText("Buscar Produto");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar Produto");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir Produto");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantidade");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Codigo");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Materia Prima");

        jFormattedTextFieldCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextFieldMedida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextFieldMedida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextFieldMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldMateria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMateriaActionPerformed(evt);
            }
        });

        jToggleButtonBuscar.setText("Buscar");
        jToggleButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBuscarActionPerformed(evt);
            }
        });

        jLabelNomeForn.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Em Gramas");

        jComboBoxTipo.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artesanal", "Industrial" }));
        jComboBoxTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(jListMateria);

        jFormattedTextFieldValidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Validade");

        jFormattedTextFieldPeso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextFieldPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Peso");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Em Gramas");

        javax.swing.GroupLayout jPanelCadastroPedidoLayout = new javax.swing.GroupLayout(jPanelCadastroPedido);
        jPanelCadastroPedido.setLayout(jPanelCadastroPedidoLayout);
        jPanelCadastroPedidoLayout.setHorizontalGroup(
            jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jFormattedTextFieldValidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextFieldMateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextFieldMedida, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldPeso, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jToggleButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40))
                            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 36, Short.MAX_VALUE))))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabelNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelERROCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        jPanelCadastroPedidoLayout.setVerticalGroup(
            jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(0, 0, 0)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelERROCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("Confirma?");

        jButtonConfirmaSim.setText("Sim");
        jButtonConfirmaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaSimActionPerformed(evt);
            }
        });

        jButtonConfirmaNao.setText("Não");
        jButtonConfirmaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfirmaLayout = new javax.swing.GroupLayout(jPanelConfirma);
        jPanelConfirma.setLayout(jPanelConfirmaLayout);
        jPanelConfirmaLayout.setHorizontalGroup(
            jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                        .addComponent(jButtonConfirmaSim)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonConfirmaNao)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelConfirmaLayout.setVerticalGroup(
            jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaSim)
                    .addComponent(jButtonConfirmaNao))
                .addContainerGap())
        );

        jButtonRemover.setText("Remover Materia Prima");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jPanelConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelCadastroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jPanelCadastroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButtonAdd.setText("Adicionar");
        jButtonAdd.setBorder(null);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaSimActionPerformed
        // TODO add your handling code here:
        if(atualizar){
            try { 
                this.atualizarProduto();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                jPanelConfirma.setVisible(false);
            }
        }if(excluir){
            try { 
                this.excluirProduto();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                jPanelConfirma.setVisible(false);
            }
        }
        
         
    }//GEN-LAST:event_jButtonConfirmaSimActionPerformed

    private void jButtonConfirmaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaNaoActionPerformed
        // TODO add your handling code here:
        atualizar = false;
        excluir = false;
        
        jPanelConfirma.setVisible(false);
    }//GEN-LAST:event_jButtonConfirmaNaoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        jPanelConfirma.setVisible(true);
        jLabelERROCPF.setText("");
        excluir = true;

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:

        jPanelConfirma.setVisible(true);
        jLabelERROCPF.setText("");
        atualizar = true;

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            this.Produto(jFormattedTextFieldCodigo.getText());
            jPanelConfirma.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        
            try {
                // TODO add your handling code here:

                this.inserirProduto();
                jPanelConfirma.setVisible(false);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
 
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
         if((jFormattedTextFieldMateria.getText().equals("") == false)
            && (jFormattedTextFieldMedida.getText().equals("") == false)
            &&buscar==true){
            String reply = "M-Prima: #"+jFormattedTextFieldMateria.getText()+"# Quantidade: #"+jFormattedTextFieldMedida.getText()+"# ---- ["+jLabelNomeForn.getText()+"]#@";
            if(!modelo.contains(reply))// Testa se o item existe na lista 
            {  
              modelo.addElement(reply);  
            }
            jListMateria.setModel(modelo);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jFormattedTextFieldMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMateriaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFormattedTextFieldMateriaActionPerformed

    private void jToggleButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBuscarActionPerformed
        // TODO add your handling code here:
        if(jToggleButtonBuscar.isSelected()){
            jToggleButtonBuscar.setText("Limpar");
            jLabelERROCPF.setText("");
            buscar = true;
            try {
                this.Materia("");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            buscar = false;
            jToggleButtonBuscar.setText("Buscar");
            jLabelERROCPF.setText("");
            jFormattedTextFieldMateria.setEditable(true);
            jLabelNomeForn.setText("");
            jFormattedTextFieldMateria.setText("");
        }
    }//GEN-LAST:event_jToggleButtonBuscarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        modelo.remove(jListMateria.getSelectedIndex());
        jListMateria.setModel(modelo);
        
    }//GEN-LAST:event_jButtonRemoverActionPerformed
    public synchronized void atualizarProduto() throws ClassNotFoundException, SQLException{
        int id;
        if((jFormattedTextFieldValor.getText().equals("") == false)
            && (jFormattedTextFieldCodigo.getText().equals("") == false)
            && (jFormattedTextFieldValidade.getText().equals("") == false)
            && (jFormattedTextFieldPeso.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new Pao(0,jFormattedTextFieldCodigo.getText(),"","","","","");
                dados = Main.atualizaMysqlProduto(dados, 3);
                
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    ListModel list = jListMateria.getModel();
                    String reply="";
                    for(int i = 0; i < list.getSize(); i++){
                         reply += list.getElementAt(i).toString();
                    }
                    dados = new Pao(dados.getIdProduto(),jFormattedTextFieldCodigo.getText(),jComboBoxTipo.getSelectedItem().toString(),
                            jFormattedTextFieldValor.getText(),jFormattedTextFieldValidade.getText(),jFormattedTextFieldPeso.getText(),reply);
                    Main.atualizaMysqlProduto(dados, 2);
                    jFormattedTextFieldValor.setText(dados.getValor());
                    jFormattedTextFieldCodigo.setText(dados.getCodigo()); 
                    jFormattedTextFieldValidade.setText(dados.getValidade());
                    jFormattedTextFieldPeso.setText(dados.getPeso());
                    jComboBoxTipo.setSelectedItem(dados.getTipo_pao());
                    String[] reply2 = dados.getMateria_prima().split("@");
                    modelo.clear();
                    jListMateria.setModel(modelo);
                     for (int i = 0; i < reply2.length; i++) {
                         modelo.addElement(reply2[i]);
                      }
                 jListMateria.setModel(modelo);
                jLabelID.setText("ID do Produto: "+dados.getIdProduto());
                jLabelERROCPF.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                   
                } else {

                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                 excluir = false; 
            }
        }
    }
    
    public synchronized void excluirProduto() throws ClassNotFoundException{
        int id;
        if((jFormattedTextFieldCodigo.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new Pao(0,jFormattedTextFieldCodigo.getText(),"","","","","");
                dados = Main.atualizaMysqlProduto(dados, 3);
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    dados = new Pao(dados.getIdProduto(),"","","","","","");
                    Main.atualizaMysqlProduto(dados, 4);
                    jFormattedTextFieldValidade.setText(""); jFormattedTextFieldMedida.setText(""); jFormattedTextFieldValor.setText("");
                    jFormattedTextFieldCodigo.setText(""); 
                    jFormattedTextFieldPeso.setText("");
                    jFormattedTextFieldMateria.setText("");
                    jFormattedTextFieldMedida.setText("");
                    modelo.clear();
                    jListMateria.setModel(modelo);
                    jLabelERROCPF.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldMateria.setText("");
                    jLabelNomeForn.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                   
                } else {

                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                 atualizar = false;
            }
        }
    }
    
    public synchronized void inserirProduto() throws ClassNotFoundException{
        int id; 
        if((jFormattedTextFieldValor.getText().equals("") == false)
            && (jFormattedTextFieldCodigo.getText().equals("") == false)
            && (jFormattedTextFieldValidade.getText().equals("") == false)
            && (jFormattedTextFieldPeso.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new Pao(0,jFormattedTextFieldCodigo.getText(),"","","","","");
                dados = Main.atualizaMysqlProduto(dados, 3);
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    jLabelERROCPF.setText("Existe um Produto com esse Código");
                    jLabelID.setText("ID do Produto: "+dados.getIdProduto());
                    jFormattedTextFieldCodigo.setEditable(true);
                } else {
                    ListModel list = jListMateria.getModel();
                    String reply="";
                    for(int i = 0; i < list.getSize(); i++){
                         reply += list.getElementAt(i).toString();
                    }
                    dados = new Pao(dados.getIdProduto(),jFormattedTextFieldCodigo.getText(),jComboBoxTipo.getSelectedItem().toString(),
                            jFormattedTextFieldValor.getText(),jFormattedTextFieldValidade.getText(),jFormattedTextFieldPeso.getText(),reply);
                    Main.atualizaMysqlProduto(dados, 1);
                    jFormattedTextFieldValidade.setText(""); jFormattedTextFieldMedida.setText(""); jFormattedTextFieldValor.setText("");
                    jFormattedTextFieldCodigo.setText(""); 
                    jFormattedTextFieldPeso.setText("");
                    jFormattedTextFieldMateria.setText("");
                    jFormattedTextFieldMedida.setText("");
                    modelo.clear();
                    jListMateria.setModel(modelo);
                    jLabelERROCPF.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldMateria.setText("");
                    jLabelNomeForn.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    public  synchronized Pao Produto(String codigo) throws ClassNotFoundException{
        try {
            dados = new Pao(0,jFormattedTextFieldCodigo.getText(),"","","","","");
            dados = Main.atualizaMysqlProduto(dados, 3);
            jFormattedTextFieldCodigo.setEditable(false);
            if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    jFormattedTextFieldValor.setText(dados.getValor());
                    jFormattedTextFieldCodigo.setText(dados.getCodigo()); 
                    jFormattedTextFieldValidade.setText(dados.getValidade());
                    jFormattedTextFieldPeso.setText(dados.getPeso());
                    jComboBoxTipo.setSelectedItem(dados.getTipo_pao());
                    String[] reply = dados.getMateria_prima().split("@");
                    modelo.clear();
                    jListMateria.setModel(modelo);
                     for (int i = 0; i < reply.length; i++) {
                         modelo.addElement(reply[i]);
                      }
                 jListMateria.setModel(modelo);
                jLabelID.setText("ID do Produto: "+dados.getIdProduto());
                jLabelERROCPF.setText("");
                jFormattedTextFieldCodigo.setEditable(true);
                
            } else {
                jLabelERROCPF.setText("Não Existe Produto com esse Código");
                jLabelID.setText("");
                jFormattedTextFieldValidade.setText(""); jFormattedTextFieldPeso.setText(""); jFormattedTextFieldValor.setText("");
                jFormattedTextFieldCodigo.setEditable(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return dados;
    }
    


    public  synchronized MateriaPrima Materia(String codigo) throws ClassNotFoundException{
        try {
            dadosf = new MateriaPrima(0,jFormattedTextFieldMateria.getText(),"","","","");
            dadosf = Main.atualizaMysqlMateriaPrima(dadosf, 3);
            jFormattedTextFieldMateria.setEditable(false);
            if(jFormattedTextFieldMateria.getText().equals(dadosf.getCodigo())){
                jLabelNomeForn.setText(dadosf.getNome());            
            } else {
                jLabelNomeForn.setText("Não Existe Materia Prima com esse Código");
                jFormattedTextFieldMateria.setEditable(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return dadosf;
    }
    


    private Pao dados;
    private MateriaPrima dadosf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonConfirmaNao;
    private javax.swing.JButton jButtonConfirmaSim;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigo;
    private javax.swing.JFormattedTextField jFormattedTextFieldMateria;
    private javax.swing.JFormattedTextField jFormattedTextFieldMedida;
    private javax.swing.JFormattedTextField jFormattedTextFieldPeso;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidade;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelERROCPF;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNomeForn;
    private javax.swing.JList<String> jListMateria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadastroPedido;
    private javax.swing.JPanel jPanelConfirma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButtonBuscar;
    // End of variables declaration//GEN-END:variables
}
