/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd;

import projetobd.Pedidos.TelaAtualizarPedidos;
import projetobd.Pedidos.TelaConsultaPedidos;
import projetobd.Pedidos.TelaCadastroPedidos;
import projetobd.Fornecedores.TelaFornecedor;
import projetobd.Funcionarios.TelaFuncionarios;
import projetobd.Cliente.TelaClientes;
import projetobd.Cliente.TelaClientesConsulta;
import projetobd.Fornecedores.TelaFornecedorConsulta;
import projetobd.Funcionarios.TelaFuncionariosConsulta;
import projetobd.MateriaPrima.TelaMateriaConsulta;
import projetobd.MateriaPrima.TelaMateriaPrima;
import projetobd.Produtos.TelaProdutos;


/**
 *
 * @author aliso
 */
public class TelaPrincipal extends javax.swing.JInternalFrame {

 
    private TelaCadastroPedidos telap1 = new TelaCadastroPedidos();   
    private TelaConsultaPedidos telap2 = new TelaConsultaPedidos();
    private TelaAtualizarPedidos telap3 = new TelaAtualizarPedidos();
    ///////////////////////////////////////////////////////////////////////////////////
    private TelaClientes telacliente = new TelaClientes();  
    private TelaClientesConsulta telacliente2 = new TelaClientesConsulta();
    ///////////////////////////////////////////////////////////////////////////////////
    private TelaFuncionarios telafuncionario = new TelaFuncionarios();  
    private TelaFuncionariosConsulta telafuncionario2 = new TelaFuncionariosConsulta();
    ///////////////////////////////////////////////////////////////////////////////////
    private TelaFornecedor telafornecedores = new TelaFornecedor();
    private TelaFornecedorConsulta telafornecedores2 = new TelaFornecedorConsulta();
    ///////////////////////////////////////////////////////////////////////////////////
    private TelaMateriaPrima telamateriaprima = new TelaMateriaPrima();
    private TelaMateriaConsulta telamateriaprima2 = new TelaMateriaConsulta();
    ///////////////////////////////////////////////////////////////////////////////////
    private TelaProdutos telamaproduto = new TelaProdutos();
    
    ///////////////////////////////////////////////////////////////////////////////////
    private TelaDashBoard  teladashboard = new TelaDashBoard();
       
       
    private boolean addOP1 = false,addOP2 = false, addOP3 = false;
    
    private boolean addOC = false,addOC2 = false;
    
    private boolean addOF1 = false, addOF2 = false;
    
    private boolean addOFF1 = false, addOFF2 = false;
    
    private boolean addOMP1 = false, addOMP2 = false;
    
    private boolean addOPT1 = false;
    
    private boolean dashboard = false;
    
    
    /**
     * Creates new form TelaPedido
     */
    public TelaPrincipal() {
        initComponents();
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        jDesktopPanePrincipal.add(teladashboard);
        teladashboard.setVisible(true);
            
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jComboBoxMateriaPrima = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBoxFuncionarios = new javax.swing.JComboBox<>();
        jComboBoxFornecedores = new javax.swing.JComboBox<>();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ventas_icon.png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButton3.setText("DashBoard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBoxProduto.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Consultar Todos" }));
        jComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutoActionPerformed(evt);
            }
        });

        jComboBoxMateriaPrima.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBoxMateriaPrima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia-Prima", "Consultar Todas" }));
        jComboBoxMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMateriaPrimaActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedidos", "Cadastrar", "Consultar", "Atualizar" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBoxFuncionarios.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBoxFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionarios", "Consultar Todos" }));
        jComboBoxFuncionarios.setBorder(null);
        jComboBoxFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionariosActionPerformed(evt);
            }
        });

        jComboBoxFornecedores.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBoxFornecedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fornecedores", "Consultar Todos" }));
        jComboBoxFornecedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedoresActionPerformed(evt);
            }
        });

        jComboBoxClientes.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes", "Consultar Todos" }));
        jComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addComponent(jComboBox1)
            .addComponent(jComboBoxClientes)
            .addComponent(jComboBoxProduto)
            .addComponent(jComboBoxMateriaPrima)
            .addComponent(jComboBoxFornecedores)
            .addComponent(jComboBoxFuncionarios)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPanePrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if ("Cadastrar".equals((String) jComboBox1.getSelectedItem()))
        {
           if(!addOP1){jDesktopPanePrincipal.add(telap1); addOP1 = true;} 
           
           telap1.setVisible(true);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
            telafuncionario.setVisible(false);
           teladashboard.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           pack();
        }
        if ("Consultar".equals((String) jComboBox1.getSelectedItem()))
        {
            if(!addOP2){jDesktopPanePrincipal.add(telap2); addOP2 = true;}
           
           telap1.setVisible(false);
           telap2.setVisible(true);
           telap3.setVisible(false);
            telacliente.setVisible(false);
            telafuncionario.setVisible(false);
           teladashboard.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           pack();
        }
        if ("Atualizar".equals((String) jComboBox1.getSelectedItem()))
        {
            if(!addOP3){jDesktopPanePrincipal.add(telap3); addOP3 = true;}
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(true);
           telacliente.setVisible(false);
           telafuncionario.setVisible(false);
           teladashboard.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           pack();
        }
  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
           telacliente.setVisible(false);
           telafuncionario.setVisible(false);
           teladashboard.setVisible(true);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionariosActionPerformed
        // TODO add your handling code here:
         if ("Funcionarios".equals((String) jComboBoxFuncionarios.getSelectedItem()))
        {
           if(!addOF1){jDesktopPanePrincipal.add(telafuncionario); addOF1 = true;} 
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
           teladashboard.setVisible(false);
           telafuncionario.setVisible(true);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           
           pack();
        }
        if ("Consultar Todos".equals((String) jComboBoxFuncionarios.getSelectedItem()))
        {
            if(!addOF2){jDesktopPanePrincipal.add(telafuncionario2); addOF2 = true;}
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
           teladashboard.setVisible(false);
           telafuncionario.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(true);
           telamateriaprima2.setVisible(false);
           
           pack();
        }
    }//GEN-LAST:event_jComboBoxFuncionariosActionPerformed

    private void jComboBoxFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedoresActionPerformed
        // TODO add your handling code here:
        if ("Fornecedores".equals((String) jComboBoxFornecedores.getSelectedItem()))
        {
           if(!addOFF1){jDesktopPanePrincipal.add(telafornecedores); addOFF1 = true;} 
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
           teladashboard.setVisible(false);
           telafuncionario.setVisible(false);
           telafornecedores.setVisible(true);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           
           pack();
        }
        if ("Consultar Todos".equals((String) jComboBoxFornecedores.getSelectedItem()))
        {
            if(!addOFF2){jDesktopPanePrincipal.add(telafornecedores2); addOFF2 = true;}
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
           teladashboard.setVisible(false);
           telafuncionario.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(true);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           
           pack();
        }
    }//GEN-LAST:event_jComboBoxFornecedoresActionPerformed

    private void jComboBoxMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMateriaPrimaActionPerformed
        // TODO add your handling code here:
        if ("Materia-Prima".equals((String) jComboBoxMateriaPrima.getSelectedItem()))
        {
           if(!addOMP1){jDesktopPanePrincipal.add(telamateriaprima); addOMP1 = true;} 
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
           teladashboard.setVisible(false);
           telafuncionario.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(true);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(false);
           telamateriaprima2.setVisible(false);
           pack();
        }
        if ("Consultar Todas".equals((String) jComboBoxMateriaPrima.getSelectedItem()))
        {
            if(!addOMP2){jDesktopPanePrincipal.add(telamateriaprima2); addOMP2 = true;}
           
           telap1.setVisible(false);
           telap2.setVisible(false);
           telap3.setVisible(false);
            telacliente.setVisible(false);
           teladashboard.setVisible(false);
           telafuncionario.setVisible(false);
           telafornecedores.setVisible(false);
           telamateriaprima.setVisible(false);
           telamaproduto.setVisible(false);
           telacliente2.setVisible(false);
           telafornecedores2.setVisible(false);
           telafuncionario2.setVisible(false);
           telamateriaprima2.setVisible(true);
           
           pack();
        }
    }//GEN-LAST:event_jComboBoxMateriaPrimaActionPerformed

    private void jComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutoActionPerformed
        // TODO add your handling code here:
        if ("Produtos".equals((String) jComboBoxProduto.getSelectedItem()))
        {
            if(!addOPT1){jDesktopPanePrincipal.add(telamaproduto); addOPT1 = true;}

            telap1.setVisible(false);
            telap2.setVisible(false);
            telap3.setVisible(false);
            telacliente.setVisible(false);
            teladashboard.setVisible(false);
            telafuncionario.setVisible(false);
            telafornecedores.setVisible(false);
            telamateriaprima.setVisible(false);
            telamaproduto.setVisible(true);
            telacliente2.setVisible(false);
            telafornecedores2.setVisible(false);
            telafuncionario2.setVisible(false);
            telamateriaprima2.setVisible(false);
            pack();
        }
        if ("Consultar Todos".equals((String) jComboBoxProduto.getSelectedItem()))
        {
            //if(!addOF2){jDesktopPanePrincipal.add(telap2); addOF2 = true;}

            telap1.setVisible(false);
            telap2.setVisible(false);
            telap3.setVisible(false);
            telacliente.setVisible(false);
            teladashboard.setVisible(false);
            telafuncionario.setVisible(false);
            telafornecedores.setVisible(false);
            telamateriaprima.setVisible(false);
            telamaproduto.setVisible(false);
            telacliente2.setVisible(false);
            telafornecedores2.setVisible(false);
            telafuncionario2.setVisible(false);
            telamateriaprima2.setVisible(false);

            pack();
        }
    }//GEN-LAST:event_jComboBoxProdutoActionPerformed

    private void jComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesActionPerformed
        // TODO add your handling code here:
        if ("Clientes".equals((String) jComboBoxClientes.getSelectedItem()))
        {
            if(!addOC){jDesktopPanePrincipal.add(telacliente); addOC = true;}

            telap1.setVisible(false);
            telap2.setVisible(false);
            telap3.setVisible(false);
            teladashboard.setVisible(false);
            telafuncionario.setVisible(false);
            telacliente.setVisible(true);
            telafornecedores.setVisible(false);
            telamateriaprima.setVisible(false);
            telamaproduto.setVisible(false);
            telacliente2.setVisible(false);
            telafornecedores2.setVisible(false);
            telafuncionario2.setVisible(false);
            telamateriaprima2.setVisible(false);
            pack();
        }
        if ("Consultar Todos".equals((String) jComboBoxClientes.getSelectedItem()))
        {
            if(!addOC2){jDesktopPanePrincipal.add(telacliente2); addOC2 = true;}

            telap1.setVisible(false);
            telap2.setVisible(false);
            telap3.setVisible(false);
            telacliente.setVisible(false);
            teladashboard.setVisible(false);
            telafuncionario.setVisible(false);
            telafornecedores.setVisible(false);
            telamateriaprima.setVisible(false);
            telamaproduto.setVisible(false);
            telacliente2.setVisible(true);
            telafornecedores2.setVisible(false);
            telafuncionario2.setVisible(false);
            telamateriaprima2.setVisible(false);

            pack();
        }

    }//GEN-LAST:event_jComboBoxClientesActionPerformed

    

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private javax.swing.JComboBox<String> jComboBoxFornecedores;
    private javax.swing.JComboBox<String> jComboBoxFuncionarios;
    private javax.swing.JComboBox<String> jComboBoxMateriaPrima;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
