/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd.MateriaPrima;

import Class.Fornecedor;
import projetobd.Fornecedores.*;
import Class.MateriaPrima;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import projetobd.Main;

/**
 *
 * @author aliso
 */
public class TelaMateriaPrima extends javax.swing.JInternalFrame {

    private boolean atualizar = false, excluir = false, buscar = false;

    /**
     * Creates new form TelaPedido
     */
    public TelaMateriaPrima() {
        initComponents();
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
  
        jPanelConfirma.setVisible(false);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCadastroPedido = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jButtonCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelERROCPF = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldCodigo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMedida = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFornecedor = new javax.swing.JFormattedTextField();
        jToggleButtonBuscar = new javax.swing.JToggleButton();
        jLabelNomeForn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelConfirma = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonConfirmaSim = new javax.swing.JButton();
        jButtonConfirmaNao = new javax.swing.JButton();

        setBorder(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setText("Materia Prima");

        jTextFieldNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jFormattedTextFieldValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jButtonCadastro.setText("Cadastrar Materia Prima");
        jButtonCadastro.setBorder(null);
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor");

        jButtonBuscar.setText("Buscar M-Prima");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar M-Prima");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir M-Prima");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Medida");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Codigo");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fornecedor");

        jFormattedTextFieldCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextFieldMedida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextFieldMedida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFormattedTextFieldFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFormattedTextFieldFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFornecedorActionPerformed(evt);
            }
        });

        jToggleButtonBuscar.setText("Buscar");
        jToggleButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBuscarActionPerformed(evt);
            }
        });

        jLabelNomeForn.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quilogramas");

        javax.swing.GroupLayout jPanelCadastroPedidoLayout = new javax.swing.GroupLayout(jPanelCadastroPedido);
        jPanelCadastroPedido.setLayout(jPanelCadastroPedidoLayout);
        jPanelCadastroPedidoLayout.setHorizontalGroup(
            jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)))
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNomeForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldValor)
                    .addComponent(jTextFieldNome)
                    .addComponent(jFormattedTextFieldCodigo)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldMedida, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelERROCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jPanelCadastroPedidoLayout.setVerticalGroup(
            jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelERROCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("Confirma?");

        jButtonConfirmaSim.setText("Sim");
        jButtonConfirmaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaSimActionPerformed(evt);
            }
        });

        jButtonConfirmaNao.setText("Não");
        jButtonConfirmaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfirmaLayout = new javax.swing.GroupLayout(jPanelConfirma);
        jPanelConfirma.setLayout(jPanelConfirmaLayout);
        jPanelConfirmaLayout.setHorizontalGroup(
            jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                        .addComponent(jButtonConfirmaSim)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonConfirmaNao)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelConfirmaLayout.setVerticalGroup(
            jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmaLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaSim)
                    .addComponent(jButtonConfirmaNao))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(jPanelConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelCadastroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(jPanelConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jPanelCadastroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        
                jPanelConfirma.setVisible(true);   
                jLabelERROCPF.setText("");
                atualizar = true; 
                
                
        

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
                jPanelConfirma.setVisible(true);   
                jLabelERROCPF.setText("");
                excluir = true; 
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConfirmaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaSimActionPerformed
        // TODO add your handling code here:
        if(atualizar){
            try { 
                this.atualizarMateriaPrima();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                jPanelConfirma.setVisible(false);
            }
        }if(excluir){
            try { 
                this.excluirMateriaPrima();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                jPanelConfirma.setVisible(false);
            }
        }
        
         
    }//GEN-LAST:event_jButtonConfirmaSimActionPerformed

    private void jButtonConfirmaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaNaoActionPerformed
        // TODO add your handling code here:
        atualizar = false;
        excluir = false;
        
        jPanelConfirma.setVisible(false);
    }//GEN-LAST:event_jButtonConfirmaNaoActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        if(buscar){
            try {
                // TODO add your handling code here:
                buscar = false;
                this.inserirMateriaPrima();
                jPanelConfirma.setVisible(false);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }  
        } else {
            jLabelERROCPF.setText("Precisa Buscar o Fornecedor");
        }
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            this.MateriaPrima(jFormattedTextFieldCodigo.getText());
            jPanelConfirma.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jFormattedTextFieldFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFornecedorActionPerformed

    private void jToggleButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBuscarActionPerformed
        // TODO add your handling code here:
        if(jToggleButtonBuscar.isSelected()){
            jToggleButtonBuscar.setText("Limpar");
            jLabelERROCPF.setText("");
            buscar = true;
            try {
                this.Fornecedor("");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            buscar = false;
            jToggleButtonBuscar.setText("Buscar");
            jLabelERROCPF.setText("");
            jFormattedTextFieldFornecedor.setEditable(true);
            jLabelNomeForn.setText("");
            jFormattedTextFieldFornecedor.setText("");
       }
    }//GEN-LAST:event_jToggleButtonBuscarActionPerformed
    public synchronized void atualizarMateriaPrima() throws ClassNotFoundException{
        int id;
        if((jTextFieldNome.getText().equals("") == false)    
            && (jFormattedTextFieldValor.getText().equals("") == false)
            && (jFormattedTextFieldCodigo.getText().equals("") == false)
            && (jFormattedTextFieldMedida.getText().equals("") == false) ){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
 
  
                    dados = new MateriaPrima(dados.getIdMT(),jFormattedTextFieldCodigo.getText(),jTextFieldNome.getText(),
                            jFormattedTextFieldMedida.getText(),jFormattedTextFieldValor.getText(),jFormattedTextFieldFornecedor.getText());
                    Main.atualizaMysqlMateriaPrima(dados, 2);
                    jTextFieldNome.setText(dados.getNome());
                    jFormattedTextFieldValor.setText(dados.getValor());
                    jFormattedTextFieldMedida.setText(dados.getMedida());
                    jFormattedTextFieldCodigo.setText(dados.getCodigo());
                    jFormattedTextFieldFornecedor.setText(dados.getFornecedor());
                    jLabelID.setText("ID da MateriaPrima: "+dados.getIdMT());
                    jLabelERROCPF.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                   
               
            } catch (SQLException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                 excluir = false; 
            }
        }
    }
    
    public synchronized void excluirMateriaPrima() throws ClassNotFoundException{
        int id;
        if((jFormattedTextFieldCodigo.getText().equals("") == false)){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new MateriaPrima(0,jFormattedTextFieldCodigo.getText(),"","","","");
                dados = Main.atualizaMysqlMateriaPrima(dados, 3);
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    dados = new MateriaPrima(dados.getIdMT(),"","","","","");
                    Main.atualizaMysqlMateriaPrima(dados, 4);
                    jTextFieldNome.setText(""); jFormattedTextFieldMedida.setText(""); jFormattedTextFieldValor.setText("");
                    jFormattedTextFieldCodigo.setText(""); 
                    jFormattedTextFieldFornecedor.setText("");
                    jLabelERROCPF.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                   
                } else {

                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                 atualizar = false;
            }
        }
    }
    
    public synchronized void inserirMateriaPrima() throws ClassNotFoundException{
        int id; 
        if((jTextFieldNome.getText().equals("") == false)    
            && (jFormattedTextFieldValor.getText().equals("") == false)
            && (jFormattedTextFieldCodigo.getText().equals("") == false)
            && (jFormattedTextFieldMedida.getText().equals("") == false) ){
            try {
                jFormattedTextFieldCodigo.setEditable(false);
                dados = new MateriaPrima(0,jFormattedTextFieldCodigo.getText(),"","","","");
                dados = Main.atualizaMysqlMateriaPrima(dados, 3);
                if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    jLabelERROCPF.setText("Existe uma MateriaPrima com esse Código");
                    jLabelID.setText("ID da MateriaPrima: "+dados.getIdMT());
                    jFormattedTextFieldCodigo.setEditable(true);
                } else {
                    dados = new MateriaPrima(dados.getIdMT(),jFormattedTextFieldCodigo.getText(),jTextFieldNome.getText(),
                            jFormattedTextFieldMedida.getText(),jFormattedTextFieldValor.getText(),jFormattedTextFieldFornecedor.getText());
                    Main.atualizaMysqlMateriaPrima(dados, 1);
                    jTextFieldNome.setText(""); jFormattedTextFieldMedida.setText(""); jFormattedTextFieldValor.setText("");
                    jFormattedTextFieldCodigo.setText(""); 
                    jLabelERROCPF.setText("");
                    jLabelID.setText("");
                    jFormattedTextFieldFornecedor.setText("");
                    jLabelNomeForn.setText("");
                    jFormattedTextFieldCodigo.setEditable(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    public  synchronized MateriaPrima MateriaPrima(String codigo) throws ClassNotFoundException{
        try {
            dados = new MateriaPrima(0,jFormattedTextFieldCodigo.getText(),"","","","");
            dados = Main.atualizaMysqlMateriaPrima(dados, 3);
            jFormattedTextFieldCodigo.setEditable(false);
            if(jFormattedTextFieldCodigo.getText().equals(dados.getCodigo())){
                    jTextFieldNome.setText(dados.getNome());
                    jFormattedTextFieldValor.setText(dados.getValor());
                    jFormattedTextFieldMedida.setText(dados.getMedida());
                    jFormattedTextFieldCodigo.setText(dados.getCodigo()); 
                    jFormattedTextFieldFornecedor.setText(dados.getFornecedor());
                jLabelID.setText("ID da MateriaPrima: "+dados.getIdMT());
                jLabelERROCPF.setText("");
                jFormattedTextFieldCodigo.setEditable(true);
                
            } else {
                jLabelERROCPF.setText("Não Existe MateriaPrima com esse Código");
                jLabelID.setText("");
                jTextFieldNome.setText(""); jFormattedTextFieldMedida.setText(""); jFormattedTextFieldValor.setText("");
                jFormattedTextFieldCodigo.setEditable(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return dados;
    }
    

    
    public  synchronized Fornecedor Fornecedor(String codigo) throws ClassNotFoundException{
        try {
            dadosf = new Fornecedor(0,jFormattedTextFieldFornecedor.getText(),"","","","");
            dadosf = Main.atualizaMysqlFornecedor(dadosf, 3);
            jFormattedTextFieldFornecedor.setEditable(false);
            if(jFormattedTextFieldFornecedor.getText().equals(dadosf.getCGC())){
                jLabelNomeForn.setText(dadosf.getNome());            
            } else {
                jLabelNomeForn.setText("Não Existe Fornecedor com esse Código");
                jFormattedTextFieldFornecedor.setEditable(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return dadosf;
    }
    
    

    private MateriaPrima dados;
    private Fornecedor dadosf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonConfirmaNao;
    private javax.swing.JButton jButtonConfirmaSim;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodigo;
    private javax.swing.JFormattedTextField jFormattedTextFieldFornecedor;
    private javax.swing.JFormattedTextField jFormattedTextFieldMedida;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelERROCPF;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNomeForn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadastroPedido;
    private javax.swing.JPanel jPanelConfirma;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JToggleButton jToggleButtonBuscar;
    // End of variables declaration//GEN-END:variables
}
